### ISSUE TITLE
Incorrect Year Month & Year Quarter Columns

### ISSUE THREAD

**Issue by SharmaAntriksh** [sql-bi/Contoso-Data-Generator#18]
The columns for Year Month & Year Quarter don't have the correct combination. I used PS version for generating 100M db

$databases += [System.Tuple]::Create(100000000, 'Contoso 100M', 'TrimCustomers', 'CutDateBefore=2010-01-01', 'CutDateAfter=2023-12-31')

![image](https://user-images.githubusercontent.com/73054674/215266295-fb7a9233-392e-4444-91ef-e7061a06d693.png)

**Comment by marcosqlbi** [comment]
The current behavior is by design.
If you expect 201001 for SQ-2010 and 201001 for Jan 2010, it's not how these columns work.
The goal of these columns is to provide a sequential integer number for every quarter/mont. This way, December 2009 is just the number for January 2010 minus 1.
