### ISSUE TITLE
Creating DB

### ISSUE THREAD

**Issue by AndreJaarconsult** [sql-bi/Contoso-Data-Generator#4]
Hi guys,
Trying to generate the Sample DB and after running the scripts (QuickRun or Generate Databases) 
what i'm doing wrong?

![image](https://user-images.githubusercontent.com/59178334/172514422-c473fa50-29eb-49a7-9208-48fec680c435.png)

**Comment by SergioMurru** [comment]
HI, the script uses the "Demo" alias to connect to the SQL Server instance.
You can create the alias or change the last line of QuickRun.ps1 by adding the parameter to specify the instance name

 
.\GenerateDatabases.ps1 -SqlDataFilesFolder $SqlDataFilesFolder -SqlBackupFolder $SqlBackupFolder -DatasetOutputFolder $DatasetOutputFolder -SqlServerInstance 'localhost'

**Comment by marcosqlbi** [comment]
@AndreJaarconsult please, can you help us to add/integrate instructions so that other people will find it easier to use the tool? We clearly may take too many things for granted, any contribution would be helpful!

**Comment by AndreJaarconsult** [comment]
Hi @marcosqlb , sure

I´ll prepare something and post here, I´ll be very happy to contribute

**Comment by AndreJaarconsult** [comment]
Hi @marcosqlbi
its Worked after updating the Db Loader

Next step is valide data and trying to understand better the config(dataset) and play with some parameters
do we have any documentation about it yet?

tomorrow i´ll write the instructions with my user POV for the step i´m so far

BRegards

**Comment by AndreJaarconsult** [comment]
@SergioMurru @marcosqlbi 
the "**" are comments for possible upgrades
basically i think a windowed .exe would make it easier for non-technical end user
if need my contact (andre@jaarconsult.com.br), will be glad to help

***** SQLBI - Contoso Generator *****
Install SQL (Any Version)
	- Download the SQL Express Edition ( https://www.microsoft.com/en-us/sql-server/sql-server-downloads )
		** Create a tutorial to install SQL or link an video
	- Install SSMS	
	- If your server instance name is different than "Demo", keep it in mind we will need it later (by default SQL server install with 'localhost' as instance name)
		** If possible, have an .exe that would first ask server instance name, than run in powershell the QuickRun script ( windows do not execute as cmd or powershell by default, users may have problems not knowing how to openwith ) 
	

Donwload the file "Contoso-Data-Generator-exe-XXXXX.zip" in https://github.com/sql-bi/Contoso-Data-Generator/releases 
	** If possible, do not use version name at the end of this file for fixed download link with lattest version, so user would not have to navegate till the end of page e seek the file.

Install 7-ZIP (  https://www.7-zip.org/ )
	- Check your windows version and just install

Intall .Net Core 3.1 https://dotnet.microsoft.com/en-us/download/dotnet/3.1

The user running Microsoft SQL Server service must have access to the SqlDataFiles folder (default C:\TEMP)
	** If possible, Run the windowed version with adminstration rights, ask user path to create a new folder and use it as default parameter (so won't need to change the security of the folder and force the user to check this permission, most of the time users don't know how to set it up)


Unzip the file "Contoso-Data-Generator-exe.zip"
Go to folder scripts
if you SQL Server Instance name is different than "Demo", Open the "QuickRun.ps1" with notepad and add: -SqlServerInstance 'NameOfTheInstance' to the very end of the file. (Changing "NameOfTheInstance" for your actual instance name)
Example: If your instance name is localhost, the last line of the file would be 
.\GenerateDatabases.ps1 -SqlDataFilesFolder $SqlDataFilesFolder -SqlBackupFolder $SqlBackupFolder -DatasetOutputFolder $DatasetOutputFolder -SqlServerInstance 'localhost'

Run "Quickrun.ps1" ( You can open with PowerShell, right click and "Execute with Powershell" )

	** Personally i think an windowed .exe executed with adminstration rights , asking a path/SQL Instance Name would solve all problems i've got so far.
	For User Version All configuration files should be in rootpath (config.json|data.xlsx|QuickRun.exe) and a folder (systemfiles) to be used by the program.

**Comment by marcosqlbi** [comment]
Please, keep the issue open otherwise it will disappear from the list of things to do.
Moreover, we'll track advancements and comments. For example, I don't think we'll create videos about installing SQL Server, we rather link existing content

**Comment by marcosqlbi** [comment]
We applied a number of improvements to the documentation and released a new version of the batch files (v 1.1).
We are not going to implement a graphical user interface - any external contribution for that would be helpful.
Thanks!
