### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by rudzimj** [sql-bi/Contoso-Data-Generator#5]
I tried to attach the MDF file to an old test server and received an error:

> The database 'Contoso 1M' cannot be opened because it is version 904. This server supports version 869 and earlier. A downgrade path is not supported. Could not open new database 'Contoso 1M'. CREATE DATABASE is aborted. (Microsoft SQL Server, Error: 948)

Can you add information about version requirements for the MDF files, bak files, and Data Generator tool?

**Comment by marcosqlbi** [comment]
I added in the release notes that SQL Server 2019 or later version is required to restore the ready-to-use .bak and mdf/ldf files.
You can use the Data Generator with other versions of SQL Server - the c# exe file generates CSV files that you can import into any database. The SQL Scripts have been tested only with SQL Server 2019, but probably you can use earlier versions with minimal adjustments.
Thanks!
